// <auto-generated />
namespace EngLishSchool.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Bug : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bug));
        
        string IMigrationMetadata.Id
        {
            get { return "201612060213512_Bug"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
